apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
  labels:
    app: insecure
spec:
  hostNetwork: true                       # ❌ Cho phép truy cập mạng host
  dnsPolicy: ClusterFirstWithHostNet     # ❌ Dùng DNS chính của host
  containers:
    - name: bad-container
      image: nginx:latest                # ❌ Dùng image `latest` không cố định version
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
          hostPort: 8080                 # ❌ Mở cổng host
      securityContext:
        privileged: true                 # ❌ Được đặc quyền root
        allowPrivilegeEscalation: true   # ❌ Có thể leo thang đặc quyền
        runAsUser: 0                     # ❌ Chạy dưới user root
        readOnlyRootFilesystem: false    # ❌ Cho phép ghi vào hệ thống file root
        capabilities:
          add:                           # ❌ Thêm capabilities nguy hiểm
            - NET_ADMIN
            - SYS_TIME
      volumeMounts:
        - name: docker-sock
          mountPath: /var/run/docker.sock  # ❌ Mount docker.sock từ host
  volumes:
    - name: docker-sock
      hostPath:
        path: /var/run/docker.sock
        type: File
