apiVersion: v1
kind: Service
metadata:
  name: insecure-service
spec:
  selector:
    app: insecure-app
  type: LoadBalancer                                # ❌ Exposes service publicly
  ports:
    - port: 80
      targetPort: 80
